apiVersion: v1
kind: Service
metadata:
  namespace: ywc
  name: core
  annotations:
    prometheus.io/scrape: "true"  
    prometheus.io/port: "80"  
spec:
  selector:
    app: core
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80