apiVersion: v1
kind: Service
metadata:
  namespace: _DYNAMIC_
  name: balancer
  annotations:
    prometheus.io/scrape: "true"  
    prometheus.io/port: "9000"
  labels:
    ywc.module: "true"
    ywc.role: "balancer"     
spec:
  selector:
    app: balancer
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8080
    name: proxy
  - protocol: TCP
    port: 81
    targetPort: 8081
    name: management
  - protocol: TCP
    port: 90
    targetPort: 8090
    name: configloader