apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRole
metadata:
  name: ywc
rules:
- apiGroups: ["extensions", "apps", ""]
  resources:
  - nodes
  - nodes/proxy
  - services
  - endpoints
  - pods
  - deployments
  - replicasets
  verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
- nonResourceURLs: ["/metrics"]
  verbs: ["get"]
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: ywc
  namespace: ywc
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: ywc
  namespace: webservice
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRoleBinding
metadata:
  name: ywc
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: ywc
subjects:
- kind: ServiceAccount
  name: ywc
  namespace: ywc
- kind: ServiceAccount
  name: ywc
  namespace: webservice  